.. change::
    :tags: bug, postgresql
    :tickets: 10717

    Adjusted the asyncpg dialect such that when the ``terminate()`` method is
    used to discard an invalidated connection, the dialect will first attempt
    to gracefully close the conneciton using ``.close()`` with a timeout, if
    the operation is proceeding within an async event loop context only. This
    allows the asyncpg driver to attend to finalizing a ``TimeoutError``
    including being able to close a long-running query server side, which
    otherwise can keep running after the program has exited.
